### ISSUE TITLE
add example of the feature label into several suites/classes

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina-demo#153]
we already have TestPriority declared and I'd like to have examples for feature as well.
@maksimsarychau knows details about registering these values via carina.
let's register 
* feature: l10n for WebLocalizationSample.java
* feature: db for DBSampleTest.java

**Comment by okamara** [comment]
<img width="474" alt="Снимок экрана 2021-04-06 в 12 19 50" src="https://user-images.githubusercontent.com/32964663/113691763-78928200-96d5-11eb-8a54-7c0b318ef65b.png">

not working in filters as I used Run name value like on screenshot, Dima made run names with small letter e.g. 
web-demo-test
feature: web, regression, acceptance

**Comment by vdelendik** [comment]
closing as won't fix
