### ISSUE TITLE
Switch carina-api demo tests to new approach with annotations

### ISSUE THREAD

**Issue by szagriychuk-ua** [zebrunner/carina-demo#205]
Currently all details for api methods are defined with old approach which uses super() constructor of AbstractApiMethods.
Needed to switch that to new approach based on annotations.
Also we can get rid of api.properties in such case.
That also should be reflected in carina-api documentation. Currently documented approach may be marked as [deprecated] in the doc. New instructions based on annotations should be added into existent paragraphs.

**Comment by akamarouski** [comment]
Api tests already use annotations
