### ISSUE TITLE
adjust pipeline env usage as example and verify/test new approach

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina-demo#211]
detais:
https://github.com/zebrunner/pipeline-ce/issues/240

we have to remove all `jenkinsPipelineEnvironments` params from sute xml files. Also we have to review and adjust matrix for those cases where this particular param was used as a filter.

**Comment by vdelendik** [comment]
merged to master. to test we have to run using ZEBRUNNER_VERSION=develop pipeline all our cron regression jobs. All jobs should be started and executed as earlier without any exceptions on launch

**Comment by okamara** [comment]
Verified, fixed.
