### ISSUE TITLE
"Mobile test - testWebView" is failed

### ISSUE THREAD

**Issue by okamara** [zebrunner/carina-demo#214]
Steps:
1. Start test job Carina Demo Tests - Mobile Sample (Android)
2. Verify that all test are passed
Actual result: "Mobile test - testWebView" is failed with error
"20:55:04 [undefined] [ERROR] TEST [Mobile test - testWebView] FAILED at [17:55:04 2022-03-23] - no such element By.xpath: //*[@class='t708__icon']
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'd97b341b943c', ip: '172.19.0.4', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1045-aws', java.version: '11.0.12'
Driver info: driver.version: unknown

com.qaprosoft.carina.core.foundation.webdriver.locator.ExtendedElementLocator.findElement(ExtendedElementLocator.java:108)
org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
com.sun.proxy.$Proxy34.click(Unknown Source)
com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement$2.doClick(ExtendedWebElement.java:1391)
com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.executeAction(ExtendedWebElement.java:1276)
com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.overrideAction(ExtendedWebElement.java:1385)
com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.doAction(ExtendedWebElement.java:1380)
com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.doAction(ExtendedWebElement.java:1360)
com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.click(ExtendedWebElement.java:510)
com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.click(ExtendedWebElement.java:499)
com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.click(ExtendedWebElement.java:490)
com.qaprosoft.carina.demo.mobile.gui.pages.android.WebViewPage.goToContactUsPage(WebViewPage.java:22)
com.qaprosoft.carina.demo.MobileSampleTest.testWebView(MobileSampleTest.java:67)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base/java.lang.reflect.Method.invoke(Method.java:566)
org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
java.base/java.lang.Thread.run(Thread.java:829)"

**Comment by akamarouski** [comment]
io.appium.java_client.NoSuchContextException: An unknown server-side error occurred while processing the command. Original error: A new session could not be created. Details: session not created: This version of ChromeDriver only supports Chrome version 102
Current browser version is 110.0.5481.154 with package name com.solvd.carinademoapplication

**Comment by akamarouski** [comment]
TEST [Mobile test - testWebView] FAILED at [17:54:34 2023-03-17] - An unknown server-side error occurred while processing the command. Original error: A new session could not be created. Details: session not created: This version of ChromeDriver only supports Chrome version 106
Current browser version is 111.0.5563.58 with package name com.solvd.carinademoapplication

**Comment by vdelendik** [comment]
we are ok with such exception. it means that administrator of the cloud (demo.zebrunner.farm) doesn't manage compatibility of the installed chrome and drivers. 
on production envs where mobile web tests are used - this one is covered successfully and all kind of auto updates for browsers are prohibited.
