### ISSUE TITLE
Sometimes logic in sequence of steps In Test is wrong

### ISSUE THREAD

**Issue by okamara** [zebrunner/carina-demo#225]
Env.: org, 7.3.20 carina
Steps:
1. Start web sample test via launcher and branch 100-200
2. Open Failed test 
3. Verify that all steps with warning, INFO, ERROR are in logical in sequence

Actual result: I see the following sequence: e.g. ERROR: Page can't be opened, then INFO: page is opened
Expected: sequence: e.g. ERROR: Page can't be opened, then no step INFO: page is opened
<img width="934" alt="Снимок экрана 2022-06-06 в 18 47 49" src="https://user-images.githubusercontent.com/32964663/172207591-0e90bf42-229a-421f-8ea9-44aa194d70a6.png">
<img width="914" alt="Снимок экрана 2022-06-06 в 19 14 24" src="https://user-images.githubusercontent.com/32964663/172207616-b1fbfbe1-058f-45df-b3b3-1b9f2a67b308.png">
<img width="929" alt="Снимок экрана 2022-06-06 в 19 42 41" src="https://user-images.githubusercontent.com/32964663/172207634-e6ad2c35-e05c-4c1c-9df9-d7031052c58d.png">

**Comment by vdelendik** [comment]
fix delivered in carina `7.3.21-SNAPSHOT` build

**Comment by okamara** [comment]
Still repro this issue: e.g. Run Web demo test with branch 100-200 with browser E99
<img width="852" alt="Снимок экрана 2022-06-13 в 16 40 55" src="https://user-images.githubusercontent.com/32964663/173367147-da783738-e671-467a-86df-d4fc4022c07a.png">
