### ISSUE TITLE
keep SoapSampleTest and declare soap.xml suite

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina-demo#228]
we already have separated https://github.com/zebrunner/carina-soap sample project using Soap. Also it was removed from carina archetype. Let's remove from carina-demo as well

**Comment by vdelendik** [comment]
after additional investigation it was discovered that current classpath and dependencies could execute soap tests correctly. 
So we decided to keep existing com.qaprosoft.carina.demo.SoapSampleTest and restore soap.xml for that. Updated ticket subject accordingly

**Comment by vdelendik** [comment]
soap.xml restored. made as part of api_regression and full_regression.
to test just run it via launcher providing `-Dsuite=soap` as one of the maven argument

**Comment by okamara** [comment]
Verified, fixed.

**Comment by vdelendik** [comment]
job is named `Soap-Demo-Test`. Verified successfully on my own using on-demand execution and inside api_regression:
![image](https://user-images.githubusercontent.com/4551455/181905990-e4353bb6-9cca-4c97-8aaa-4637543cbed3.png)
