### ISSUE TITLE
"Amazon-Demo-Test" failed with "Error Code: 403"

### ISSUE THREAD

**Issue by ghost** [zebrunner/carina-demo#303]
Steps:
1. Start "Amazon-Demo-Test" via Jenkins
2. Test is failed with error message:

"com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: TG9FXYFJSXVSEQFW; S3 Extended Request ID: fmYLeFOLarn3uZFB4DLevogRLwyPmh3AFmYrxalzt3uDa9fE1Ts9MuoSnBVtOHkefHkKuqnuo7"

**Comment by akamarouski** [comment]
wontfix
