### ISSUE TITLE
Web tests on android device is without video

### ISSUE THREAD

**Issue by okamara** [zebrunner/carina-demo#328]
Env.: carina-demo 8.0.8, develop branch
Steps:
1. Execute Web demo test on android, chrome browser
Actual result: WEb demo test completed, video is not available
Expected result: video is available

e.g. https://okr666.zebrunner.org/projects/DEF/automation-launches/287/tests/1867?runsState=cGFnZT0x

**Comment by akamarouski** [comment]
verified, fixed

**Comment by okamara** [comment]
Verified on org env, video is not available https://okr666.zebrunner.org/projects/DEF/automation-launches/613/tests/12200?runsState=cGFnZT0x

**Comment by okamara** [comment]
Re-verified, fixed.
