### ISSUE TITLE
Web demo test on mobile device "testModelSpecs" failed 

### ISSUE THREAD

**Issue by ghost** [zebrunner/carina-demo#329]
env.: carina-demo version 8.0.8, develop branch
Steps:
1. Execute Web demo test on mobile device android
2. Verify that "testModelSpecs" passed
Actual result: "testModelSpecs" failed 
Expected: "testModelSpecs" passed

test -> https://okr666.zebrunner.org/projects/DEF/automation-launches/287/tests/1868?runsState=cGFnZT0x

**Comment by akamarouski** [comment]
wontfix
