### ISSUE TITLE
Web test failed with error "org.openqa.selenium.NoSuchSessionException: invalid session id..."

### ISSUE THREAD

**Issue by ghost** [zebrunner/carina-demo#356]
Web test failed with error "org.openqa.selenium.NoSuchSessionException: invalid session id..."
http://3.126.150.168/test-runs/6/tests/22?runsState=eyIjIjpudWxsLCJhY3RpdmVUZXN0UnVuSWQiOjYsImZyb21XaXphcmQiOm51bGx9

**Comment by akamarouski** [comment]
wontfix
